package com.cora.stylefinder.member.auth;
import com.cora.stylefinder.member.auth.dto.*; import com.cora.stylefinder.member.common.ApiException; import com.cora.stylefinder.member.config.JwtService; import com.cora.stylefinder.member.member.*; import com.cora.stylefinder.member.member.dto.MemberResponse; import io.jsonwebtoken.*; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class AuthService { private final UserRepository users; private final RefreshTokenRepository tokens; private final PasswordEncoder encoder; private final JwtService jwt; public AuthService(UserRepository u,RefreshTokenRepository t,PasswordEncoder e,JwtService j){users=u;tokens=t;encoder=e;jwt=j;}
 public MemberResponse signup(SignupRequest r){if(users.existsByEmail(r.email()))throw new ApiException("EMAIL_ALREADY_EXISTS","이미 사용 중인 이메일입니다.",HttpStatus.CONFLICT);return MemberResponse.from(users.save(new User(r.email().toLowerCase(),encoder.encode(r.password()),r.displayName())));}
 public TokenResponse login(LoginRequest r){User u=users.findByEmail(r.email().toLowerCase()).orElseThrow(this::invalidCredentials);if(!encoder.matches(r.password(),u.getPasswordHash()))throw invalidCredentials();return issue(u);}
 public TokenResponse refresh(RefreshRequest r){try{Claims c=jwt.parse(r.refreshToken());if(!"refresh".equals(c.get("type",String.class)))throw invalidRefresh();RefreshToken saved=tokens.findByTokenHash(hash(r.refreshToken())).orElseThrow(this::invalidRefresh);if(!saved.isUsable())throw invalidRefresh();saved.revoke();return issue(saved.getUser());}catch(ExpiredJwtException e){throw new ApiException("REFRESH_TOKEN_EXPIRED","로그인이 만료되었습니다.",HttpStatus.UNAUTHORIZED);}catch(JwtException e){throw invalidRefresh();}}
 public void logout(User u,String refresh){if(refresh==null||refresh.isBlank())throw invalidRefresh();RefreshToken token=tokens.findByTokenHash(hash(refresh)).orElseThrow(this::invalidRefresh);if(!token.getUser().getId().equals(u.getId()))throw new ApiException("FORBIDDEN","권한이 없습니다.",HttpStatus.FORBIDDEN);token.revoke();}
 public MemberResponse me(User u){return MemberResponse.from(u);} private TokenResponse issue(User u){String refresh=jwt.refreshToken(u.getId());tokens.save(new RefreshToken(u,hash(refresh),Instant.now().plusSeconds(1209600)));return new TokenResponse(jwt.accessToken(u.getId(),u.getRole().name()),refresh,"Bearer",jwt.accessSeconds());} private ApiException invalidCredentials(){return new ApiException("INVALID_CREDENTIALS","이메일 또는 비밀번호가 올바르지 않습니다.",HttpStatus.UNAUTHORIZED);} private ApiException invalidRefresh(){return new ApiException("REFRESH_TOKEN_INVALID","유효하지 않은 Refresh Token입니다.",HttpStatus.UNAUTHORIZED);} private String hash(String value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
