package com.cora.stylefinder.member.activity;
import com.cora.stylefinder.member.common.ApiException; import com.cora.stylefinder.member.member.User; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/members") public class ActivityController { private final SearchHistoryRepository histories; private final SavedResultRepository saved; public ActivityController(SearchHistoryRepository h,SavedResultRepository s){histories=h;saved=s;}
 @GetMapping("/search-histories") List<Map<String,Object>> histories(@AuthenticationPrincipal User u){return histories.findByUserOrderBySearchedAtDesc(u).stream().map(x->Map.<String,Object>of("id",x.getId())).toList();}
 @PostMapping("/search-histories") ResponseEntity<Void> addHistory(@AuthenticationPrincipal User u,@RequestBody HistoryRequest r){histories.save(new SearchHistory(u,r.searchType(),r.cropMode()));return ResponseEntity.status(HttpStatus.CREATED).build();}
 @DeleteMapping("/search-histories/{id}") ResponseEntity<Void> removeHistory(@AuthenticationPrincipal User u,@PathVariable Long id){SearchHistory x=histories.findById(id).orElseThrow(()->new ApiException("SEARCH_HISTORY_NOT_FOUND","검색 기록을 찾을 수 없습니다.",HttpStatus.NOT_FOUND)); if(x.user!=u)throw new ApiException("FORBIDDEN","권한이 없습니다.",HttpStatus.FORBIDDEN); histories.delete(x);return ResponseEntity.noContent().build();}
 @GetMapping("/saved-results") List<Map<String,Object>> saved(@AuthenticationPrincipal User u){return saved.findByUserOrderByIdDesc(u).stream().map(x->Map.<String,Object>of("id",x.getId())).toList();}
 @PostMapping("/saved-results") ResponseEntity<Void> addSaved(@AuthenticationPrincipal User u,@Valid @RequestBody SavedRequest r){if(saved.existsByUserAndCatalogItemId(u,r.catalogItemId()))throw new ApiException("DUPLICATE_SAVED_RESULT","이미 저장한 결과입니다.",HttpStatus.CONFLICT);saved.save(new SavedResult(u,r.catalogItemId(),r.title(),r.imageUrl(),r.sourceUrl(),r.similarityScore(),r.modelVersion(),r.metadata().toString()));return ResponseEntity.status(HttpStatus.CREATED).build();}
 @DeleteMapping("/saved-results/{id}") ResponseEntity<Void> removeSaved(@AuthenticationPrincipal User u,@PathVariable Long id){SavedResult x=saved.findById(id).orElseThrow(()->new ApiException("SAVED_RESULT_NOT_FOUND","저장한 결과를 찾을 수 없습니다.",HttpStatus.NOT_FOUND));if(x.user!=u)throw new ApiException("FORBIDDEN","권한이 없습니다.",HttpStatus.FORBIDDEN);saved.delete(x);return ResponseEntity.noContent().build();}
 record HistoryRequest(String searchType,String cropMode){} record SavedRequest(@NotBlank String catalogItemId,@NotBlank String title,@NotBlank String imageUrl,String sourceUrl,double similarityScore,@NotBlank String modelVersion,Map<String,Object> metadata){}
}
